---
:project:
    :use_exceptions: FALSE
    :use_test_preprocessor: TRUE
    :use_auxiliary_dependencies: TRUE
    :build_root: build
    :release_build: TRUE
    :test_file_prefix: test_
    :default_tasks:
        - release
:release_build:
    :output: vsk.a
:paths:
    :test:
        - +:test/**
        - -:test/support
    :source:
        - src/**
    :include:
        - src/**
    :support:
        - test/support
:defines:
    :commmon: &common_defines []
    :test:
        - *common_defines
        - TEST
    :test_preprocess:
        - *common_defines
        - TEST
:tools:
    :release_compiler:
        :executable: gcc
        :arguments:
            - -I"$": COLLECTION_PATHS_INCLUDE
            - -DGNU_COMPILER
            - -c ${1}
            - -o ${2}
            - -MMD
            - -MF ${4}
            - -std=c99
            - -Wall
            - -Wextra
            - -Werror
            - -pedantic
:cmock:
    :mock_prefix: mock_
    :when_no_prototypes: :warn
    :when_ptr: :compare_ptr
    :enforce_strict_ordering: TRUE
    :treat_externs: :include
    :plugins:
        - :ignore
        - :callback
        - :ignore_arg
    :treat_as:
        uint8: HEX8
        uint16: HEX16
        uint32: UINT32
        int8: INT8
        bool: UINT8
:gcov:
    :reports:
        - HtmlDetailed
    :gcovr:
        :html_medium_threshold: 75
        :html_high_threshold: 90
:plugins:
    :load_paths:
        - "#{Ceedling.load_path}"
    :enabled:
        - xml_tests_report
        - stdout_pretty_tests_report
        - module_generator
        - gcov
        - compile_commands_json
